user1 = User.create!(email: "rails@pick.com", password: "password")
user2 = User.create!(email: "ruby@pick.com", password: "password")
user3 = User.create!(email: "php@pick.com", password: "password")

user1.pharmacies.create!(nickname: "deko", age: "23", sex: "女", counseling: "喉が痛い", sick: "sore_throat")
user2.pharmacies.create!(nickname: "cool", age: "35", sex: "男", counseling: "熱がある", sick: "fever")
user3.pharmacies.create!(nickname: "pita", age: "38", sex: "女", counseling: "咳が止まらない", sick: "cough")
user1.pharmacies.create!(nickname: "pako", age: "28", sex: "女", counseling: "喉が痛い", sick: "sore_throat")
user2.pharmacies.create!(nickname: "hata", age: "29", sex: "男", counseling: "咳が止まらない", sick: "cough")
user3.pharmacies.create!(nickname: "hige", age: "19", sex: "女", counseling: "熱がある", sick: "fever") 
