user1 = User.create!(email: "rails@pick.com", password: "password")
user2 = User.create!(email: "ruby@pick.com", password: "password")
user3 = User.create!(email: "php@pick.com", password: "password")
user4 = User.create!(email: "java@pick.com", password: "password")
user5 = User.create!(email: "python@pick.com", password: "password")
user6 = User.create!(email: "javascript@pick.com", password: "password")
user7 = User.create!(email: "swift@pick.com", password: "password")
user8 = User.create!(email: "github@pick.com", password: "password")
user9 = User.create!(email: "prg@pick.com", password: "password")
user10 = User.create!(email: "charlesdegaulle@pick.com", password: "password")


user1.pharmacies.create!(nickname: "山ちゃん", age: "23", sex: "女", counseling: "喉が痛い", sick: "sore_throat")
user2.pharmacies.create!(nickname: "かっちゃん", age: "35", sex: "男", counseling: "熱がある", sick: "fever")
user3.pharmacies.create!(nickname: "大将", age: "48", sex: "男", counseling: "咳が止まらない", sick: "cough")
user4.pharmacies.create!(nickname: "みきゃん", age: "25", sex: "女", counseling: "鼻水が止まらない", sick: "sneeze")
user5.pharmacies.create!(nickname: "さんちゃん", age: "17", sex: "男", counseling: "頭痛がする", sick: "headache")
user6.pharmacies.create!(nickname: "しんちゃん", age: "27", sex: "女", counseling: "肩こりがよくならない", sick: "shoulder_pain")
user7.pharmacies.create!(nickname: "麦ちゃん", age: "25", sex: "男", counseling: "胃痛がひどい", sick: "stomachache")
user8.pharmacies.create!(nickname: "大名", age: "45", sex: "女", counseling: "腰痛がよくならない", sick: "ones_back_hurts")
user9.pharmacies.create!(nickname: "りんちゃん", age: "18", sex: "男", counseling: "目がゴロゴロする", sick: "something_rolling_around_in_my_eye")
user10.pharmacies.create!(nickname: "サーちゃん", age: "29", sex: "女", counseling: "ものもらい", sick: "stye")
