user1 = User.create!(email: "rails@pick.com", password: "password")
user2 = User.create!(email: "ruby@pick.com", password: "password")
user3 = User.create!(email: "php@pick.com", password: "password")
user4 = User.create!(email: "java@pick.com", password: "password")
user5 = User.create!(email: "python@pick.com", password: "password")
user6 = User.create!(email: "javascript@pick.com", password: "password")
user7 = User.create!(email: "swift@pick.com", password: "password")
user8 = User.create!(email: "github@pick.com", password: "password")
user9 = User.create!(email: "prg@pick.com", password: "password")
user10 = User.create!(email: "charlesdegaulle@pick.com", password: "password")
user11 = User.create!(email: "c4@pick.com", password: "password")
user12 = User.create!(email: "hl@pick.com", password: "password")
user13 = User.create!(email: "cs@pick.com", password: "password")
user14 = User.create!(email: "ps@pick.com", password: "password")
user15 = User.create!(email: "ir@pick.com", password: "password")
user16 = User.create!(email: "dw@pick.com", password: "password")
user17 = User.create!(email: "vw@pick.com", password: "password")
user18 = User.create!(email: "ac@pick.com", password: "password")


user1.pharmacies.create!(nickname: "山ちゃん", age: "23", sex: "女", counseling: "喉が痛い", sick: "sore_throat")
user2.pharmacies.create!(nickname: "かっちゃん", age: "35", sex: "男", counseling: "熱がある", sick: "fever")
user3.pharmacies.create!(nickname: "大将", age: "48", sex: "男", counseling: "咳が止まらない", sick: "cough")
user4.pharmacies.create!(nickname: "みきゃん", age: "25", sex: "女", counseling: "鼻水が止まらない", sick: "sneeze")
user5.pharmacies.create!(nickname: "さんちゃん", age: "17", sex: "男", counseling: "頭痛がする", sick: "headache")
user6.pharmacies.create!(nickname: "しんちゃん", age: "16", sex: "女", counseling: "歯が痛い", sick: "dental_pain")
user7.pharmacies.create!(nickname: "麦ちゃん", age: "19", sex: "男", counseling: "胃痛がひどい", sick: "stomachache")
user8.pharmacies.create!(nickname: "大名", age: "45", sex: "女", counseling: "胃もたれがする", sick: "stodginess")
user9.pharmacies.create!(nickname: "りんちゃん", age: "18", sex: "男", counseling: "目がゴロゴロする", sick: "something_rolling_around_in_my_eye")
user10.pharmacies.create!(nickname: "サーちゃん", age: "29", sex: "女", counseling: "ものもらい", sick: "stye")
user11.pharmacies.create!(nickname: "ユンちゃん", age: "39", sex: "男", counseling: "目が疲れる", sick: "eyestrain")
user12.pharmacies.create!(nickname: "こんちゃん", age: "27", sex: "女", counseling: "肩こり", sick: "ones_back_hurts")
user13.pharmacies.create!(nickname: "御影さん", age: "56", sex: "男", counseling: "腰痛", sick: "shoulder_pain")
user14.pharmacies.create!(nickname: "りくさん", age: "36", sex: "女", counseling: "眠れない", sick: "can_not_sleeping")
user15.pharmacies.create!(nickname: "船場さん", age: "58", sex: "男", counseling: "のどが痛い", sick: "sore_throat")
user16.pharmacies.create!(nickname: "目黒さん", age: "37", sex: "女", counseling: "熱がある", sick: "fever")
user17.pharmacies.create!(nickname: "cチャンネル", age: "20", sex: "男", counseling: "せきがひどい", sick: "cough")
user18.pharmacies.create!(nickname: "るーちゃん", age: "21", sex: "女", counseling: "頭が痛い", sick: "headache")
